### ISSUE TITLE
Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.7.0.0

### ISSUE THREAD

**Issue by jcansdale** [madskristensen/AutoLoadPackageManager#2]
I'm seeing the following when I click on `View > Package Load Explorer`:

![image](https://user-images.githubusercontent.com/11719160/41747017-69099cec-75a4-11e8-8ed8-0223d37b136d.png)

![image](https://user-images.githubusercontent.com/11719160/41747130-caef4df8-75a4-11e8-9149-f5a84c1e7854.png)

```
1835 | ERROR | SetSite failed for package [AutoLoadPackageManagerPackage]Source: 'AutoLoadPackageManager' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Threading, Version=15.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'    at AutoLoadPackageManager.AutoLoadPackageManagerPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)    at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass17_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)    at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)    at Microsoft.VisualStudio.Services.VsTask.GetResult()  WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
-- | -- | --
```

```
Microsoft Visual Studio Enterprise 2017 
Version 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Visual C++ 2017   00369-60000-00001-AA512
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.40511.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.0.40502.0
Azure Functions and Web Jobs Tools

BuildVision   2.1.1.157
Building process visualization.

C# Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Clear MEF Component Cache   1.4
Clears the Visual Studio MEF component cache to fix issues with cache corruption.

Command Explorer   1.0
Provides a tool window to explorer all commands, groups and menus to help extension authors place commands/buttons in the desired location

Commit Formatter   1.0
Adds automatic word wrap to the Git commit message textbox.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

FormatDocumentOnSave   1.0
Enables auto formatting of the code when you save a file. Visual Studio supports auto formatting of the code with the CTRL+E,D or CTRL+E,F key shortcuts but with this extension the command 'Format Document' is executed on Save.

You can find the source here: https://github.com/Elders/VSE-FormatDocumentOnSave

GitHub.VisualStudio   2.5.4.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

KnownMonikers Explorer   1.0.18
A tool window for Visual Studio extension authors to explore the KnownMonikers image collection

Learn the Shortcut   1.4.28
Shows how easy you can make the same action using only the keyboard. Displays the keyboard shortcut for any command that you execute to help you learn the shortcuts you need the most.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NCrunch   
Continuous Testing Tool for .NET
Copyright © 2010-2018 Remco Software Ltd

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Package Load Explorer   1.0.999
Shows information about how VS packages are loaded in Visual Studio.

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Registry Explorer   1.0
Provides a tool window that shows the Visual Studio registry hive. This is useful for developers writing extensions for Visual Studio. Requires Visual Studio 2017.6

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

TestDriven.Net   4.3
Zero friction testing for Visual Studio

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9
Visual C++ for Linux Development

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 56f97a8dd4353d897336941f3e644423b87c794f.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

VSPackage1 Extension   1.0
VSPackage1 Visual Studio Extension Detailed Info

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info
```

**Comment by jcansdale** [comment]
That was quick! Confirmed working. 👍

I like being able to see what settings other packages are using.

**Comment by beemobile4net** [comment]
I have practically the same problem. I am using Visual Studio 2022 v. 17.2.12.

![VS2022Error](https://user-images.githubusercontent.com/110674451/225599349-40979945-52f4-4777-a0a8-2aef09a65033.png)

The mentioned log file contains this error:

SetSite failed for package [AvaloniaPackage]Source: 'AvaloniaVS.VS2022' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at AvaloniaVS.AvaloniaPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress) at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

It looks like the Visual Studio extension has troubles finding an assembly which it depends on:
Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

What can I do to fix this, please? Restarting Visual Studio did not help.

Thank you.

**Comment by adsgray70** [comment]
beemobile4net This issue has been closed.  But I have exactly the same issue as you, I have not found a solution but it was working then it broke.  Have tried repairing VS but no luck.  Tried installing Avalonia from admin command prompt with no luck.  To diagnose I open with no project then go to Tools Options, Avalonia Xaml Editor, and get this error, so it's not on the loading of a project.  I'll post back here when I find a solution or a decent thread.

**Comment by beemobile4net** [comment]
Hello adsgray70, thank you for your feedback and sharing your experience. 

1. I see that the issue is marked as closed, however, it would be worth considering reopening it, as (at least from my point of view), it is still unresolved.
2. I "resolved" it by installing Visual Studio 2019, in which everything works as expected. We target .NET 5.0 with our project, so it does not bother me. But naturally, I would prefer to use the latest (VS 2022), if it wasn't for this problem.
3. I too have not been able to resolve the problem as of yet.
Thank you.

**Comment by adsgray70** [comment]
Thanks beemobile4net, I was about to do the same thing, ride it out on 2019 until a fix came along.  Good to know that 2019 works.

**Comment by adsgray70** [comment]
Got some news.  I have installed uninstalled Avalonia Extentions, then reinstalled a VSIX I have which intalls versoni 0.10.18 it is 1,492Kb and I downloaded it on 2023-01-15.  This works, (test is to go to Tools -->Options Avalonia Extentions and if it doesn't throw and error its working.  Loaded a Project and it works.   

However close and reopen Visual Studio and it fails.  When I go to Manage Extensions the version is now 0.10.18.2, I don't know why I have turned off Automatic extension update.

The latest version of Avalonia Extensions I have is guess what? 0.10.18.2  .
So it looks like the version is being cached and updated.  

So if you want to use it Uninstall Avalonia Extensions and shut down VS and install the 0.10.18 version. Then don't close it down.  My next decision it to use it this way till a fix comes out or down grade to 2019.  

Good Luck.  If I find some time I might see if I can gut the latest version out of my apps data or where ever its living.

Ads

**Comment by beemobile4net** [comment]
Hello Ads,

thank you again for sharing this exciting news. Could you advice on where to get Avalonia Extentions v. 0.10.18 from?

Thanks!

**Comment by beemobile4net** [comment]
OK, so I have finally got it to work on Visual Studio 2022 too. I had to update my Visual Studio Professional to v. 17.5.3 (which is I believe the latest version at the time of writing this post). However, there is more to it. 
I have been using LTSC version of Visual Studio 2022 (LTSC stands for Long-Term Servicing Channel), which means the following:
The Long-Term Servicing Channel (LTSC) is designed for Windows 10 devices and use cases where the key requirement is that functionality and features don’t change over time (source: https://techcommunity.microsoft.com/t5/windows-it-pro-blog/ltsc-what-is-it-and-when-should-it-be-used/ba-p/293181). This means, that Visual Studio Updater was keeping my VS version at 17.2.something. So the solution was to change this updater setting.
Help -> Check For Updates -> Change Update Settings -> Update Channel -> switch from "LTSC" to "Current"

Maybe this helps.

Thank you.

**Comment by adsgray70** [comment]
Hi beemobile4net
I'm well versed in LTSC, We use it at work on a mine for our 7/24 mining systems in a DMZ.  We have around 60 servers and 20 workstations.  The workstations are LTSC Win 10 OS for our control room,  it's about 10 years support with no functional updates, security only.  Similar with our servers if we choose off years we get limited updates.  We rarely if ever do updates, and certainly no unplanned updates.  There is no Internet, Email or Office Apps available on the DMZ, so this is a good fit for LTSC.  If you were developing a major application, then LTSC would be a good option, then port it to a recent version before publishing.  VS LTSC would probably be required if your developing on Windows 10 LTSC as there would no updates.  

I'm at version 17.3.6 VS with the same problem.  My last update was 2022-10-30 so its been in limbo for a while.  When I click change settings, the update channel was Current with an option of Past but no LTSC.   

I've now updated and my quick check (tools-->options) has worked twice which is a good sign.  
Thanks for all your help.

**Comment by beemobile4net** [comment]
Hey Ads, very interesting!

So did the update from LTSC help you too to resolve the problem?

In that case, you're absolutely welcome. Hopefully this post will help other developers who may be dealing with the same problem.

Happy coding!

**Comment by adsgray70** [comment]
Hey Bee, I was not on VS_LTSC but on Current_17.3.6 which hadn't been updated since 2022-10-30.  I'm sure I did a uninstall-reinstall or a repair of VS but that was the last install date.  The latest is an update not an install.  

Probably best to keep all updates in sync; for instance, if using LTSC then have all other updates turned off.  If working in a group have an updated strategy and procedure.  I'm sure there will be some good reading on this in blogs dedicated to DEV-OPS.

Ads
